

use MOMS_FLOWER_SHOP.ANALYTICS;
create or replace view MOMS_FLOWER_SHOP.ANALYTICS.DIM_CUSTOMERS as (SELECT DISTINCT EVENT_ID , CUSTOMER_ID
FROM MOMS_FLOWER_SHOP.STAGING.INAPP_EVENTS
WHERE EVENT_NAME = 'place_order');

